name: refill

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: تشغيل سكربت إعادة التعبئة
        run: php refill.php
        env:
          SMMBIND_API_KEY: ${{ secrets.SMMBIND_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
