name: refill

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: تشغيل سكربت إعادة التعبئة
        run: php refill.php
        env:
          SMMBIND_API_KEY: ${{ secrets.SMMBIND_API_KEY }}
